apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.ovirt.org
  labels:
    app.kubernetes.io/instance: ovirt.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-ovirt
    app.kubernetes.io/name: ovirt-csi-driver
    app.kubernetes.io/component: csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
