---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ovirt.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-ovirt
    app.kubernetes.io/name: ovirt-csi-driver
    app.kubernetes.io/component: health-monitor-controller-cluster-role
  name: csi-ovirtplugin-node-health-monitor-controller-cluster-role
  namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
- kind: ServiceAccount
  name: csi-ovirtplugin-node-sa
  namespace: openshift-cluster-csi-drivers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ovirt.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-ovirt
    app.kubernetes.io/name: ovirt-csi-driver
    app.kubernetes.io/component: health-monitor-controller-role
  name: csi-ovirtplugin-node-health-monitor-controller-role
  namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
- kind: ServiceAccount
  name: csi-ovirtplugin-node-sa
  namespace: openshift-cluster-csi-drivers



---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovirt-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: csi-ovirtplugin-node-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: ovirt-privileged-role
  apiGroup: rbac.authorization.k8s.io
