apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-sc
  namespace: openshift-cluster-csi-drivers
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.ovirt.org
parameters:
  # the name of the oVirt storage domain. "Test storage domain" is used by the oVirt engine mock.
  storageDomainName: "OCP_STORAGE"
  thinProvisioning: "true"
  fsType: "ext4"
