apiVersion: v1 
kind: Pod 
metadata:
  name: testpodwithcsi
  namespace: openshift-cluster-csi-drivers
spec:
  containers:
  - image: busybox
    name: testpodwithcsi
    command: ["sh", "-c", "while true; do ls -la /opt; echo this file system was made availble using ovirt-csi-driver; sleep 1m; done"]
    imagePullPolicy: Always
    volumeMounts:
    - name: pv0002
      mountPath: "/opt"
    resources:
      limits:
        cpu: 10m
        memory: 100Mi
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: 1g-ovirt-cow-disk
